<?xml version="1.0"?>
<robot name="walkernew" xmlns:xacro="http://www.ros.org/wiki/xacro">
<origin xyz="0 0 0" rpy="0 0 0"/>

<!-- Table of Contents - (ctrl-f to jump)

Property List:
    Constants
    Walker Configuration Dimensions

Plugins:
    Gazebo Ros Controls
    Wheel Encoder

Links & Joints:
    Base Coordinate Systems             [BCS]
    Core                                [CORE]
    Track Extenders                     [TR_EX]
    Front Legs                          [FR_LGS]
    Back Legs                           [BK_LGS]
    Front Wheels                        [FR_WLS]
    Back Wheels                         [BK_WLS]
    Handle Tracks                       [HN_TRS]
    Handles                             [HNDLS]
    Kinect Camera                       [KNCT]

Transmissions:
    Right Turning Wheel                 [RTW_T]
    Left Turning Wheel                  [LTW_T]
    Right Spinning Wheel                [RSW_T]
    Left Spinning Wheel                 [LSW_T]
    Back Right Spinning Wheel           [BRSW_T]
    Back Left Spinning Wheel            [BLSW_T]

Physics Params:
    Wheels (Kp Kd mu1 mu2 etc.)
    
-->

<!-- PROPERTY LIST -->
<!--All units in m-kg-s-radians unit system -->
<property name="M_PI" value="3.1415926535897931" />
<property name="inch" value="0.0254"/>

<!-- List of Editable Walker Dimensions-->
<property name="forward_leg_extension" value="${4*inch}" />
<property name="backwards_leg_extension" value="${4*inch}" />
<property name="frame_width" value="${3*inch}" />
<property name="handle_width" value="${3*inch}" />
<property name="extrusion_length" value="0.038" />
<property name="axle_track" value="${15*inch}" />

<!-- Just defining wheel base is one thing, however in order to define
     The position of each wheel w.r.t the position of the core, one must
     Define both forward and backward wheel extension, and they add up to wheel base
     Here we define wheel base and backward wheel extension, forward is implicitly defined -->

<property name="wheel_base" value="0.5" />
<property name="front_wheel_extension" value="0" />

<property name="handle_track" value="${20*inch}" />
<property name="handle_height" value="${43*inch}" />
<property name="core_width" value="${0.25431 * 2}" />

<!--    Gazebo Ros Control Plugin
        Allows us to generate controllers for joints
        Controllers will be nodes within the /walkernew namespace    -->

<gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/walkernew</robotNamespace>
        <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
</gazebo>

<!-- Base Coordinate Systems    :   [BCS]    -->
<link name="base_footprint">
    <origin xyz="0 0 0" rpy="0 0 0" />
</link>

<property name="base_link_height_offset" value="${21.25 * inch}" />
<joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_link_height_offset}" rpy="0 0 0" />
</joint>

<link name="base_link">
    <origin xyz="0 0 0" rpy="0 0 0" />
</link>

<!-- It would be nice to import things like mass, Ixx Ixy, etc. from a yaml file, or some text file that could be fully or partially generated from solidworks... Unfortunately, there is no support for .yaml files in indigo, but there is in jade, and hopefully that feature will eventually be backported. If it is ever backported, look into grabbing those properties straight form a yaml file)-->
<xacro:macro name="alink" params="linkName fileName transformXYZ transformRPY mass ixx ixy ixz iyy iyz izz">
<link name="${linkName}">
    <visual>
        <origin xyz="${transformXYZ}" rpy="${transformRPY}"/>
        <geometry>
            <mesh filename="${fileName}" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="${transformXYZ}" rpy="${transformRPY}"/>
        <geometry>
            <mesh filename="${fileName}" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
		<origin xyz="${transformXYZ}" rpy="${transformRPY}"/>
        <mass value="${mass}"/>
        <inertia ixx="${ixx}" ixy="${ixy}" ixz="${ixz}" iyy="${iyy}" iyz="${iyz}" izz="${izz}" />
    </inertial>
</link>
</xacro:macro>

<xacro:macro name="transmissionMacro" params="tName jointName type">
<transmission name="${tName}">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${jointName}">
        <hardwareInterface>${type}JointInterface</hardwareInterface>
    </joint>
    <actuator name="${tName}_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>${type}JointInterface</hardwareInterface>
    </actuator>
</transmission> 
</xacro:macro>

<!-- Core   :   [CORE]  -->
<joint name="link_to_core" type="fixed">
    <parent link="base_link"/>
    <child link="core"/>
    <origin xyz="0 ${-0.5 * core_width} 0" rpy="0 0 0" />
</joint>

<xacro:alink 
    linkName="core"
    fileName="package://simplified/meshes/Core.STL"
    transformXYZ="0.02504 ${0.5 * core_width} 0.01849"
    transformRPY="0 0 0"
    mass="7.6"
    ixx="0.91" ixy="0" ixz="0" iyy="0.47" iyz="-0.37" izz="0.46"
/>

<!-- Track Extenders    :   [TR_EX] -->
<property name="track_extender_wheel_offset" value="${2.7*inch}" /> 
<property name="track_extender_padding_thickness" value="0.00955" />

<xacro:macro name="trackExtender" params="prefix reflect rotate">
<xacro:alink 
    linkName="track_extender_${prefix}"
    fileName="package://simplified/meshes/CoreToLeg.STL"
    transformXYZ="-0.0057 ${0.06219 * reflect} 0.027"
    transformRPY="0 0 ${rotate*M_PI}"
    mass="1.56"
    ixx="0.03" ixy="0" ixz="0" iyy="0" iyz="0" izz="0.3"
/>
</xacro:macro>
<xacro:trackExtender prefix="right" reflect =  "1" rotate="0"/>
<xacro:trackExtender prefix="left"  reflect = "-1" rotate="1"/>

<joint name="core_to_right_track_extender" type="fixed">
    <parent link="core"/>
    <child link="track_extender_right"/>
    <origin xyz="0 ${-0.5 * (axle_track - core_width)} ${-2 * (track_extender_padding_thickness + extrusion_length)}"/>
</joint>

<joint name="core_to_left_track_extender" type="fixed">
    <parent link="core"/>
    <child link="track_extender_left"/>
    <origin xyz="0 ${1 * core_width + 0.5 * (axle_track - core_width)} ${-2 * (track_extender_padding_thickness + extrusion_length)}"/>
</joint>

<!-- Front Legs     :   [FR_LGS]    -->
<property name="front_leg_length" value="0.399108" />
<xacro:macro name="trackExtenderToFrontLegJoint" params="prefix">
<joint name="track_extender_to_front_leg_${prefix}" type="fixed">
    <parent link="track_extender_${prefix}"/>
    <child link="front_${prefix}_leg"/>
    <origin xyz="${0.2 + front_wheel_extension - front_leg_length} 0 0"/>
</joint>
</xacro:macro>
<xacro:trackExtenderToFrontLegJoint prefix="right"/>
<xacro:trackExtenderToFrontLegJoint prefix="left"/>

<xacro:alink 
    linkName="front_right_leg"
    fileName="package://simplified/meshes/Left Front Leg.STL"
    transformXYZ="0.22295 -0.00299 -0.03424"
    transformRPY="0 0 ${M_PI / -2}"
    mass="2.04"
    ixx="0.08" ixy="-0.06" ixz="0.07" iyy="0.18" iyz="-0.04" izz="0.17"
/>

<xacro:alink 
    linkName="front_left_leg"
    fileName="package://simplified/meshes/Right Front Leg.STL"
    transformXYZ="0.22295 0.00299 -0.03424"
    transformRPY="0 0 0"
    mass="2.04"
    ixx="0.08" ixy="-0.06" ixz="0.07" iyy="0.18" iyz="-0.04" izz="0.18"
/>

<!-- Back Legs      :   [BK_LGS] -->
<property name="back_leg_length" value="0.300" />
<property name="back_leg_tip_to_over_wheel_offset" value="0" />

<xacro:macro name="frontToBackLegJoint" params="prefix">
<joint name="${prefix}_front_to_back_leg" type="fixed">
    <parent link="front_${prefix}_leg"/>
    <child link="back_${prefix}_leg"/>
    <origin xyz="${back_leg_length - (wheel_base - front_leg_length) - back_leg_tip_to_over_wheel_offset} 0 ${-1 * extrusion_length}"/>
</joint>
</xacro:macro>
<xacro:frontToBackLegJoint prefix="right"/>
<xacro:frontToBackLegJoint prefix="left"/>

<xacro:alink 
    linkName="back_right_leg"
    fileName="package://simplified/meshes/Left Back Leg.STL"
    transformXYZ="-0.1947 -0.00554 -0.06712"
    transformRPY="0 0 ${M_PI/-2}"
    mass="2.11"
    ixx="0.04" ixy="0" ixz="0" iyy="0.07" iyz="0" izz="0.04"
/>

<xacro:alink 
    linkName="back_left_leg"
    fileName="package://simplified/meshes/Right Back Leg.STL"
    transformXYZ="-0.1947 0.00554 -0.06712"
    transformRPY="0 0 0"
    mass="2.11"
    ixx="0.04" ixy="0" ixz="0" iyy="0.07" iyz="0" izz="0.04"
/>

<!-- Front Wheels           [FR_WLS]  -->
<property name="front_wheel_rotation_joint_offset" value="0.000" />
<property name="front_wheel_carriage_to_axle_z_offset" value ="-0.14" />
<property name="front_wheel_carriage_to_axle_x_offset" value ="-0.075" />

<xacro:macro name="frontwheelassembly" params="prefix reflect">
<!-- Wheel Carriage (Yaw)-->
<joint name="${prefix}_front_leg_to_wheel_carriage" type="continuous">
    <parent link="front_${prefix}_leg"/>
    <child link="front_${prefix}_wheel_carriage"/>
    <origin xyz="${front_leg_length - front_wheel_rotation_joint_offset} ${0.02 * reflect} ${-0.15 - extrusion_length}"/>
    <axis xyz="0 0 1" />
    <limit effort="100.0" velocity="100.0"  />
    <joint_properties damping="0.5" friction="0.01"/>    
</joint>

<xacro:alink 
    linkName="front_${prefix}_wheel_carriage"
    fileName="package://simplified/meshes/WheelAssembly.STL"
    transformXYZ="-0.03285 0.00018 -0.04182"
    transformRPY="0 0 0"
    mass="2.03"
    ixx="0.06" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.02"
/>
<xacro:transmissionMacro 
    tName="${prefix}_turning_wheel" 
    jointName="${prefix}_front_leg_to_wheel_carriage" 
    type="Position"
/>

<!-- Wheel (Forward/Backward Rotation)-->
<joint name="front_${prefix}_carriage_to_wheel" type="continuous">
    <parent link="front_${prefix}_wheel_carriage"/>
    <child link="front_${prefix}_wheel"/>
    <origin xyz="${front_wheel_carriage_to_axle_x_offset} 0 ${front_wheel_carriage_to_axle_z_offset}"/>
    <limit effort="100.0" velocity="100.0"  />
    <joint_properties damping="0.1" friction="0.2"/>
    <axis xyz="0 1 0" />
</joint>

<xacro:alink 
    linkName="front_${prefix}_wheel"
    fileName="package://simplified/meshes/wheel.STL"
    transformXYZ="0 0 0"
    transformRPY="0 0 0"
    mass="2.03"
    ixx="0.06" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.02"
/>
<xacro:transmissionMacro 
    tName="${prefix}_spinning_wheel" 
    jointName="front_${prefix}_carriage_to_wheel" 
    type="Velocity"
/>

</xacro:macro>

<xacro:frontwheelassembly prefix="right" reflect="-1" />
<xacro:frontwheelassembly prefix="left" reflect="1" />                      

<!-- Back Wheels [BK_WLS] -->
<xacro:macro name="backwheel" params="prefix reflect">
<joint name="back_${prefix}_leg_to_wheel" type="continuous">
    <parent link="back_${prefix}_leg"/>
    <child link="back_${prefix}_spinning_wheel"/>
    <origin xyz="${-1 * back_leg_length} ${reflect * 0.02} -0.3"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.1" friction="0.5"/>
    <axis xyz="0 1 0" />
</joint>

<xacro:alink 
    linkName="back_${prefix}_spinning_wheel"
    fileName="package://simplified/meshes/wheel.STL"
    transformXYZ="0 0 0"
    transformRPY="0 0 0"
    mass="2.03"
    ixx="0.06" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.02"
/>

<xacro:transmissionMacro 
    tName="back_${prefix}_spinning_wheel" 
    jointName="back_${prefix}_leg_to_wheel" 
    type="Effort"
/>

</xacro:macro>
<xacro:backwheel prefix="right" reflect="-1"/>
<xacro:backwheel prefix="left" reflect="1" />                       

<!-- Handle Tracks [HN_TRS] -->

<property name="handle_track_height" value="0.345459" />

<joint name="core_to_right_handle_track" type="fixed">
    <parent link="core"/>
    <child link="right_handle_track"/>
    <origin xyz="0 ${core_width / 2 - handle_track / 2} ${handle_track_height}"/>
</joint>

<xacro:alink 
    linkName="right_handle_track"
    fileName="package://simplified/meshes/Handle Bottom.STL"
    transformXYZ="0 0.04906 -0.23033"
    transformRPY="0 0 0"
    mass="2.11"
    ixx="0.04" ixy="0" ixz="0" iyy="0.07" iyz="0" izz="0.04"
/>

<joint name="core_to_left_handle_track" type="fixed">
    <parent link="core"/>
    <child link="left_handle_track"/>
    <origin xyz="0 ${core_width / 2 + handle_track / 2} ${handle_track_height}"/>
</joint>

<xacro:alink 
    linkName="left_handle_track"
    fileName="package://simplified/meshes/Handle Bottom.STL"
    transformXYZ="0 -0.04906 -0.23033"
    transformRPY="0 0 ${M_PI}"
    mass="2.11"
    ixx="0.04" ixy="0" ixz="0" iyy="0.07" iyz="0" izz="0.04"
/>                           

<!-- Handles  [HNDLS] -->
<property name="handle_track_offset_from_ground" value="${base_link_height_offset + handle_track_height}" />
<xacro:macro name="handleLink" params="prefix">

<joint name="${prefix}_handle_track_to_link" type="fixed">
    <parent link="${prefix}_handle_track"/>
    <child link="${prefix}_handle"/>
    <origin xyz="${extrusion_length * 2} 0 ${handle_height - handle_track_offset_from_ground}"/>
</joint>

<xacro:alink 
    linkName="${prefix}_handle"
    fileName="package://simplified/meshes/HandleAssembly.STL"
    transformXYZ="-0.06475 0 -0.15606"
    transformRPY="0 0 0"
    mass="2.03"
    ixx="0.06" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.02"
/>
</xacro:macro>
<xacro:handleLink prefix="right" />
<xacro:handleLink prefix="left" />

<!-- Kinect Camera    [KNCT] -->
<xacro:include filename="$(find simplified)/urdf/kinectCam.urdf.xacro"/>

<!-- params cam_p* control position, cam_o* control orientation -->
<xacro:sensor_kinect parent="core" 
    cam_px="0.02" cam_py="${core_width / 2}" cam_pz="0.31"
    cam_or="0" cam_op="0" cam_oy="0" />

<!--        END OF LINKS / JOINTS
            BEGINNING OF TRANSMISSIONS  & OTHER    -->

<xacro:macro name="wheelRefs" params="refName">
<gazebo reference="${refName}">
    <mu1>0.99</mu1>
    <mu2>0.9</mu2>
    <kp>1000000</kp>
    <kd>500000</kd>
    <fdir1>1 0 0</fdir1>
    <gravity>true</gravity>
    <dampingFactor>0.10</dampingFactor>
    <material>Gazebo/Black</material>
    <provideFeedback>true</provideFeedback>
</gazebo>
</xacro:macro>

<xacro:wheelRefs refName="front_left_spinning_wheel"/>
<xacro:wheelRefs refName="front_right_spinning_wheel"/>
<xacro:wheelRefs refName="back_right_spinning_wheel"/>
<xacro:wheelRefs refName="back_left_spinning_wheel"/> 

</robot>